import "./globals.css";
import Head from "next/head";
import Layout from "@/utils/Layout";

export const metadata = {
  title: "Rida Rafi Syed",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Head>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        />
      </Head>
      <html lang="en">
        <body>
          <Layout>{children}</Layout>
        </body>
      </html>
    </>
  );
}
